name: Validate with Hassfest

on:
  push:
    paths:
      - "custom_components/**"
      - "hacs.json"
      - ".github/workflows/hassfest.yml"
  pull_request:
    paths:
      - "custom_components/**"
      - "hacs.json"
  workflow_dispatch:

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@main
        # Als 'v1' niet werkt in jouw omgeving, gebruik:
        # uses: home-assistant/actions/hassfest@main
